- name: Install necessary packages (both OSes)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools
    - python-pip
    - openssh-server

- name: Install required pip libraries
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - urllib3
