---
# tasks file for ansible-role-foxpass
- name: Set OS Version (CentOS)
  set_fact:
    os_version: "{{ ansible_facts['distribution_major_version'] }}"
  when: ansible_facts['distribution'] == 'CentOS'

- name: Set OS Version (Ubuntu)
  set_fact:
    os_version: "{{ ansible_facts['distribution_version'] }}"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Download FoxPass setup script
  get_url:
    url: "https://raw.githubusercontent.com/foxpass/foxpass-setup/master/linux/{{ ansible_facts['distribution'] | lower }}/{{ os_version }}/foxpass_setup.py"
    dest: /tmp/foxpass_setup.py
    mode: 0755

- name: Install CentOS specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
  when: ansible_facts['distribution'] == 'CentOS'

- name: Install Ubuntu specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-utils
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install necessary packages (both OSes)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools
    - python-pip
    - openssh-server

- name: Install required pip libraries
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - urllib3

- name: Run FoxPass setup script
  command: "python foxpass_setup.py --base-dn {{ foxpass_base_dn }} --bind-user {{ foxpass_bind_user }} --bind-pw {{ foxpass_bind_pw }} --api-key {{ foxpass_api_key }}"
  args:
    chdir: /tmp/
    creates: /etc/sudoers.d/95-foxpass-sudo
