---
# tasks file for ansible-role-foxpass

- include_tasks: install-centos.yml
  when: ansible_os_family == 'CentOS'

- include_tasks: install-ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

# Specifically tested on Amazon Lightsail "amazon_linux_2018_03_0_2"
- include_tasks: install-amzn.yml
  when: ansible_os_family == 'Amazon' and ansible_facts['distribution_major_version'] == '2018'

- include_tasks: install-common.yml

- name: Download FoxPass setup script
  get_url:
    url: "https://raw.githubusercontent.com/foxpass/foxpass-setup/master/linux/{{ os_version }}/foxpass_setup.py"
    dest: /tmp/foxpass_setup.py
    mode: 0700

- name: Run FoxPass setup script
  command: "python /tmp/foxpass_setup.py --base-dn {{ foxpass_base_dn }} --bind-user {{ foxpass_bind_user }} --bind-pw {{ foxpass_bind_pw }} --api-key {{ foxpass_api_key }}"
  args:
    creates: /etc/sudoers.d/95-foxpass-sudo

- name: "Setup SUDOers support (optional: {{ foxpass_setup_SUDOers }})"
  include: setupSUDOers.yml
  when: foxpass_setup_SUDOers
